apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master.statestore.svc.cluster.local:6379
  - name: redisPassword
    value: YOUR_PASSWORD
  - name: actorStateStore
    value: "true"
